apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-dev-deployment
  namespace: kubeapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
        - name: kubeapp-container
          image: vedantmatanhelia/kubeapp:dev
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: kubeapp-config
            - secretRef:
                name: kubeapp-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"