apiVersion: v1
kind: Service
metadata:
  name: kubeapp-service
  namespace: kubeapp-dev
spec:
  type: NodePort
  selector:
    app: kubeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080